# 数据库坐标（因为 Docker 暴露了 3306 端口到本机，所以可以直接用 localhost）
spring.datasource.url=jdbc:mysql://localhost:3306/crossborder_pay?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
# 数据库钥匙
spring.datasource.url=jdbc:mysql://localhost:3306/crossborder_pay?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root1234
# 机械臂的底层引擎设置
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis 叹息之墙配置
spring.data.redis.host=localhost
spring.data.redis.port=6379
